version: '3'
services:
  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - postgres:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    networks:
      - infra
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - infra
volumes:
  postgres:
    driver: local
networks:
  infra:
    driver: bridge