version: '3'
services:
  postgress:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - postgres:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    networks:
      - infra
volumes:
  postgres:
    driver: local
networks:
  infra:
    driver: bridge